### ISSUE TITLE
Only works with Rails >= 4.2

### ISSUE THREAD

**Issue by carlosramireziii** [yhirano55/rspec-validates_timeliness#13]
The `ValidatorProxy` object [calls `validate`](https://github.com/yhirano55/rspec-validates_timeliness/blob/master/lib/rspec-validates_timeliness/matchers/validator_proxy.rb#L28) on the Active Record model, however this method was added to the Active Record API in Rails 4.2. 

For Rails versions 4.1 or below, a `NoMethodError: undefined method 'validate'` is raised. 

Since `validate` is [an alias for `valid?`](http://api.rubyonrails.org/v4.2.0/classes/ActiveModel/Validations.html#method-i-validate) perhaps a fix would be to use `valid?` instead?

**Comment by say8425** [comment]
```ruby
gem 'rspec-validates_timeliness', github: 'say8425/rspec-validates_timeliness'
```

@carlosramireziii Use my [forked gem](https://github.com/say8425/rspec-validates_timeliness).
